# Dependencies
# redcarpet | kramdown
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Daniel Chia 
tagline:          'Human'
description:      "Hi, I'm Daniel. Here's where I rant."
baseurl:          /
url:              http://danielcodes.github.io

author:
  name:           'Daniel Chia'
  email:          'danielarmandochia@gmail.com'
  url:            ''
  github:         'https://github.com/danielcodes'
  bitbucket:      'https://bitbucket.org/danielcodes/'
  twitter:        'https://twitter.com/danielchiaa'

paginate:         5

